-- DDL FOR SNOWFLAKE DWH

CREATE SCHEMA IF NOT EXISTS staging;

CREATE OR REPLACE TABLE staging.catalog (
    product_id INT PRIMARY KEY,
    product_model STRING,
    product_type STRING,
    product_price NUMBER(10,2)
);

CREATE OR REPLACE TABLE staging.customers (
    customer_id INT PRIMARY KEY,
    first_name STRING NOT NULL,
    last_name STRING NOT NULL,
    email STRING NOT NULL,
    segment STRING NOT NULL
);

CREATE OR REPLACE TABLE staging.sales_data (
    id NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    customer_id INT NOT NULL,
    quantity INT NOT NULL,
    price NUMBER(10,2) NOT NULL,
    time_stamp TIMESTAMP_NTZ NOT NULL,
    channel STRING NOT NULL,
    promo_code STRING NOT NULL,
    discount_percent NUMBER(5,2) NOT NULL
);

-- DDL for analytics layer

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_MODEL VARCHAR(100) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SEGMENT VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    DATE DATE NOT NULL,
    DAY_OF_WEEK VARCHAR(10) NOT NULL,
    CALENDAR_MONTH INT NOT NULL,
    CALENDAR_YEAR INT NOT NULL,
    WEEKDAY_INDICATOR VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_CHANNEL (
    CHANNEL_ID INT AUTOINCREMENT PRIMARY KEY,
    CHANNEL_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_PROMOTION (
    PROMO_ID INT AUTOINCREMENT PRIMARY KEY,
    PROMO_CODE VARCHAR(20) NOT NULL,
    DISCOUNT_PERCENT DECIMAL(5,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.FACT_SALES (
    SALES_ID INT AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_PRODUCT(PRODUCT_ID),
    CUSTOMER_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_CUSTOMER(CUSTOMER_ID),
    DATE_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_DATE(DATE_ID),
    CHANNEL_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_CHANNEL(CHANNEL_ID),
    PROMO_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_PROMOTION(PROMO_ID),
    PRODUCT_QUANTITY INT NOT NULL,
    PRODUCT_PRICE DECIMAL(10,2) NOT NULL
);

