-- DDL FOR SNOWFLAKE DWH

CREATE SCHEMA IF NOT EXISTS staging;

CREATE OR REPLACE TABLE staging.catalog (
    product_id INT PRIMARY KEY,
    product_model STRING,
    product_type STRING,
    product_price NUMBER(10,2)
);

CREATE OR REPLACE TABLE staging.customers (
    customer_id INT PRIMARY KEY,
    first_name STRING NOT NULL,
    last_name STRING NOT NULL,
    email STRING NOT NULL,
    segment STRING NOT NULL
);

CREATE OR REPLACE TABLE staging.sales_data (
    id NUMBER(38,0) AUTOINCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    customer_id INT NOT NULL,
    quantity INT NOT NULL,
    price NUMBER(10,2) NOT NULL,
    time_stamp TIMESTAMP_NTZ NOT NULL,
    channel STRING NOT NULL,
    promo_code STRING NOT NULL,
    discount_percent NUMBER(5,2) NOT NULL
);

-- DDL for analytics layer

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_MODEL VARCHAR(100) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SEGMENT VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    DATE DATE NOT NULL,
    DAY_OF_WEEK VARCHAR(10) NOT NULL,
    CALENDAR_MONTH INT NOT NULL,
    CALENDAR_YEAR INT NOT NULL,
    WEEKDAY_INDICATOR VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_CHANNEL (
    CHANNEL_ID INT AUTOINCREMENT PRIMARY KEY,
    CHANNEL_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.DIM_PROMOTION (
    PROMO_ID INT AUTOINCREMENT PRIMARY KEY,
    PROMO_CODE VARCHAR(20) NOT NULL,
    DISCOUNT_PERCENT DECIMAL(5,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS SOFTCART_DWH.ANALYTICS.FACT_SALES (
    SALES_ID INT AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_PRODUCT(PRODUCT_ID),
    CUSTOMER_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_CUSTOMER(CUSTOMER_ID),
    DATE_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_DATE(DATE_ID),
    CHANNEL_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_CHANNEL(CHANNEL_ID),
    PROMO_ID INT NOT NULL REFERENCES SOFTCART_DWH.ANALYTICS.DIM_PROMOTION(PROMO_ID),
    PRODUCT_QUANTITY INT NOT NULL,
    PRODUCT_PRICE DECIMAL(10,2) NOT NULL
);

-- Data Movement from staging to analytics layer
INSERT INTO SOFTCART_DWH.ANALYTICS.DIM_CHANNEL (CHANNEL_NAME)
SELECT DISTINCT CHANNEL
FROM SOFTCART_DWH.STAGING.SALES_DATA;

INSERT INTO SOFTCART_DWH.ANALYTICS.DIM_CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, SEGMENT)
SELECT DISTINCT CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, SEGMENT
FROM SOFTCART_DWH.STAGING.CUSTOMERS;

INSERT INTO SOFTCART_DWH.ANALYTICS.DIM_PRODUCT (PRODUCT_ID, PRODUCT_MODEL, PRODUCT_TYPE)
SELECT DISTINCT PRODUCT_ID, PRODUCT_MODEL, PRODUCT_TYPE
FROM SOFTCART_DWH.STAGING.CATALOG;

INSERT INTO SOFTCART_DWH.ANALYTICS.DIM_PROMOTION (PROMO_CODE, DISCOUNT_PERCENT)
SELECT DISTINCT PROMO_CODE, DISCOUNT_PERCENT
FROM SOFTCART_DWH.STAGING.SALES_DATA;

INSERT INTO SOFTCART_DWH.ANALYTICS.DIM_DATE (DATE_ID, DATE, DAY_OF_WEEK, CALENDAR_MONTH, CALENDAR_YEAR, WEEKDAY_INDICATOR)
SELECT DISTINCT
    EXTRACT(YEAR FROM TIME_STAMP) * 10000 + EXTRACT(MONTH FROM TIME_STAMP) * 100 + EXTRACT(DAY FROM TIME_STAMP) AS DATE_ID,
    TIME_STAMP::DATE AS DATE,
    DAYNAME(TIME_STAMP) AS DAY_OF_WEEK,
    EXTRACT(MONTH FROM TIME_STAMP) AS CALENDAR_MONTH,
    EXTRACT(YEAR FROM TIME_STAMP) AS CALENDAR_YEAR,
    CASE WHEN DAYOFWEEK(TIME_STAMP) IN (0, 6) THEN 'Weekend' ELSE 'Weekday' END AS WEEKDAY_INDICATOR
FROM SOFTCART_DWH.STAGING.SALES_DATA;

INSERT INTO SOFTCART_DWH.ANALYTICS.FACT_SALES
    (PRODUCT_ID, CUSTOMER_ID, DATE_ID, CHANNEL_ID, PROMO_ID, PRODUCT_QUANTITY, PRODUCT_PRICE)
SELECT
    SD.PRODUCT_ID,
    SD.CUSTOMER_ID,
    (EXTRACT(YEAR FROM SD.TIME_STAMP) * 10000 + EXTRACT(MONTH FROM SD.TIME_STAMP) * 100 + EXTRACT(DAY FROM SD.TIME_STAMP))::INT,
    DC.CHANNEL_ID,
    DP.PROMO_ID,
    SD.QUANTITY,
    SD.PRICE
FROM SOFTCART_DWH.STAGING.SALES_DATA SD
JOIN SOFTCART_DWH.ANALYTICS.DIM_CHANNEL DC
    ON SD.CHANNEL = DC.CHANNEL_NAME
JOIN SOFTCART_DWH.ANALYTICS.DIM_PROMOTION DP
    ON SD.PROMO_CODE = DP.PROMO_CODE
    AND SD.DISCOUNT_PERCENT = DP.DISCOUNT_PERCENT;
